const express = require("express");
const UserController = require("../app/http/controllers/userController.js");
const JobController = require("../app/http/controllers/jobController.js");

const JobCandidatesController = require("../app/http/controllers/jobCandidatesController.js");
const DepartmentController = require("../app/http/controllers/departmentController.js");
const DesignationController = require("../app/http/controllers/designationController.js");
const EmployeeController = require("../app/http/controllers/employeeController.js");
const checkUserAuth = require("../app/http/middlewares/authUser.js");
const projectController = require("../app/http/controllers/projectController.js");
const User = require("../app/models/User.js");
const EmployeeActionController = require("../app/http/controllers/employeeActionController.js");
const CustomerController = require("../app/http/controllers/customerController.js");
const AssetController = require("../app/http/controllers/assetController.js");
const EmployeeAssetController = require("../app/http/controllers/employeeAssetController.js");
const EmployeeProjectController = require("../app/http/controllers/employeeProjectController.js");
const FileIssueController = require("../app/http/controllers/FileController.js");
const employeeRelationController = require("../app/http/controllers/employeeRelationController.js");
const plotController = require("../app/http/controllers/plotController.js");
const userRoleController = require("../app/http/controllers/userRoleController.js");
const conversionUserController = require("../app/http/controllers/conversionUserController.js");
const leaveController = require("../app/http/controllers/leaveController.js");
const multer = require("multer");
const AttendanceController = require("../app/http/controllers/attendenceController.js");
const attendanceController = require("../app/http/controllers/attendenceController.js");
const MemberController = require("../app/http/controllers/memberController.js");
const NomineeController = require("../app/http/controllers/nomineeController.js");
const UnitCategory = require("../app/models/Unit_Category.js");
const UnitCategoryController = require("../app/http/controllers/unitCategoryController.js");
const UnitTypeController = require("../app/http/controllers/unitTypeController.js");
const FloorController = require("../app/http/controllers/FloorController.js");
const Upload = require("../app/http/middlewares/Storages.js");
const BlockController = require("../app/http/controllers/blockController.js");
const StreetController = require("../app/http/controllers/streetController.js");
const UnitController = require("../app/http/controllers/unitController.js");
const adminAuth = require("../app/http/middlewares/admin.js");
const adminHrAuth = require("../app/http/middlewares/adminHr.js");
const AssetTypeController = require("../app/http/controllers/assetTypeController.js");
const ProjectTaskController = require("../app/http/controllers/projectTaskController.js");
const MultiProjectTaskController = require("../app/http/controllers/MultiProjectTaskController.js");
const PackageController = require("../app/http/controllers/packagesController.js");
const BookingController = require("../app/http/controllers/bookingController.js");
const UnVarifiedTransactionController = require("../app/http/controllers/unVarifiedTransactionController.js");
const TransactionController = require("../app/http/controllers/TransactionController.js");
const PhaseController = require("../app/http/controllers/phaseController.js");
const SectorController = require("../app/http/controllers/sectorController.js");
const UnitNatureTypeController = require("../app/http/controllers/unitNatureTypeController.js");
const PlotSizeController = require("../app/http/controllers/plotSizeController.js");
const VoucherController = require("../app/http/controllers/voucherController.js");
const VoucherTypeController = require("../app/http/controllers/voucherTypeController.js");
const VoucherReasonController = require("../app/http/controllers/voucherReasonController.js");
const FileSubmissionController = require("../app/http/controllers/FileSubmissionController.js");
const InstallmentReceiptsController = require("../app/http/controllers/Installment_ReceiptsController.js");
const InstallmentTypeController = require("../app/http/controllers/InstallmentTypeController.js");
const PaymentModeController = require("../app/http/controllers/PaymentModeController.js");
const CustomerProjectController = require("../app/http/controllers/customerProjectController.js");
const policyController = require("../app/http/controllers/policyController.js");
const AccountCategoryController = require("../app/http/controllers/accountCategoryController.js");
const AccountTransactionController = require("../app/http/controllers/accountTransactionController.js");
const EmployeeSalaryHistoryController = require("../app/http/controllers/employeeSalaryHistoryController.js");
const SettingsController = require("../app/http/controllers/settingsController.js");
const memberAddressController = require("../app/http/controllers/memberAddressController.js");
// const DispatchedSalariesController = require("../app/http/controllers/DispatchedSalariesController.js");
const ExpenseCategoryController = require("../app/http/controllers/expenseCategoryController.js");
const IncomeCategoryController = require("../app/http/controllers/incomeCategoryController.js");
const NdcChangesController = require("../app/http/controllers/ndcChangesController.js");
const UserGroupController = require("../app/http/controllers/userGroupController.js");
const MenuController = require("../app/http/controllers/menuController.js");
const GroupMenuController = require("../app/http/controllers/groupMenuController.js");
const TaxPayeeController = require("../app/http/controllers/taxPayeeCategoryController.js");
const TaxTagController = require("../app/http/controllers/taxTagController.js");
const FileTransferController = require("../app/http/controllers/fileTransferController.js");
const TransferFeeController = require("../app/http/controllers/TRFSController.js");
const LocationContollers = require("../app/http/controllers/locationController.js");
const LiabilityController = require("../app/http/controllers/liabilityController.js");
const PayOffController = require("../app/http/controllers/payOffController.js");
const WithdrawalController = require("../app/http/controllers/withdrawalController.js");
const WithdrawController = require("../app/http/controllers/withdrawController.js");

const upload = multer({ dest: "uploads/" });
const router = express.Router();

router.post("/test", UserController.test);
router.post("/ballot", UserController.ballotSearch);
router.post("/genrate", UserController.generate);
router.post("/login", UserController.Login);
router.post("/change", UserController.changePassword);
router.post("/expire", UserController.timeExpire);
router.post("/file/get", FileIssueController.getFiles); //Create and Add new file
// router.post("/surcharge", UserController.surcharges); //Create and Add new file

router.get("/booking/id/getStatementFile", BookingController.createStatement);

router.post("/booking/plotNoAllot", BookingController.plotNumberAllot);
router.post("/booking/locationAssign", BookingController.locationAssign);

module.exports = router;
